name: CI


on:
  push:
    branches: [ main ]

jobs:
  integrationTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm start &
      - run: npx newman run test/arms-sales-statsAPI-TEST.json
      - run: npx newman run test/attacks_statsAPI_TEST.json
      - run: npx newman run test/homicidesAPI-TEST.json
      - run: node test/e2e.js
      - run: node test/e2eIvan.js


